//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickUp
    {
        public int PickUpID { get; set; }
        public string StreetAdress { get; set; }
        public string City { get; set; }
        public int PickupCapacity { get; set; }
    }
}
